version: '3'
services:
  postgredb:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=sbs
      - POSTGRES_PASSWORD=CpZrKPUuQZYzVHTchPkQ
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
 
